apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-app
  template:
    metadata:
      labels:
        app: restaurant-app
    spec:
      containers:
        - name: restaurant-app
          image: chahatrajput3008/restaurant-project-restaurant-app:latest
          imagePullPolicy: Always   # ensures new image is pulled
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-service:27017/restaurant"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: restaurant-secrets
                  key: jwt-secret
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
            - name: TRUST_PROXY
              value: "true"
            - name: COOKIE_SECURE
              value: "false"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_ENV
              value: "production"
            - name: DD_SERVICE
              value: "restaurant-app"
            - name: DD_VERSION
              value: "1.0.0"
          # Optional: add probes to avoid CrashLoopBackOff due to slow start
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  selector:
    app: restaurant-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
