apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-app
  template:
    metadata:
      labels:
        app: restaurant-app
    spec:
      containers:
        - name: restaurant-app
          image: chahatrajput3008/restaurant-project-restaurant-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-service:27017/restaurant"
            - name: JWT_SECRET
              value: "my-strong-password-for-jwt-key"
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  selector:
    app: restaurant-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
