version: '3.8'

services:
  # Restaurant Application (Development Mode)
  restaurant-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: restaurant_app_dev
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/restaurant
      - JWT_SECRET=my-strong-password-for-jwt-key
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      mongodb:
        condition: service_healthy
      seed-db:
        condition: service_completed_successfully
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - ./public:/app/public
      - ./views:/app/views
    command: npm run dev
    networks:
      - restaurant-network
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/

  # MongoDB Database (Development)
  mongodb:
    image: mongo:7-jammy
    container_name: restaurant_mongodb_dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=restaurant
    volumes:
      - mongodb_data_dev:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/restaurant --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - restaurant-network

  # Database Seeder (Development)
  seed-db:
    build: .
    container_name: restaurant_seeder_dev
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/restaurant
      - JWT_SECRET=my-strong-password-for-jwt-key
      - NODE_ENV=development
    depends_on:
      mongodb:
        condition: service_healthy
    command: ["node", "scripts/seed-database.js"]
    restart: "no"
    networks:
      - restaurant-network

  # MongoDB Express (Database Admin Interface)
  mongo-express:
    image: mongo-express:latest
    container_name: restaurant_mongo_express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - restaurant-network

volumes:
  mongodb_data_dev:
    driver: local

networks:
  restaurant-network:
    driver: bridge
